---
title: "05_rarefaction"
output: html_document
---
```{r}
library(vegan)


# 1. Keep only rows with >0 species
nonzero_idx <- rowSums(bee_matrix) > 0
bee_matrix_nonzero <- bee_matrix[nonzero_idx, ]
bee_data_nonzero   <- bee_data[nonzero_idx, ]

# 2. Split by site
mat_control <- bee_matrix_nonzero[bee_data_nonzero$site == "control", ]
mat_focal   <- bee_matrix_nonzero[bee_data_nonzero$site == "focal", ]

# First plot: Control
rarecurve(mat_control,
          step = 1,
          col = "orange",
          cex = 0.6,
          label = FALSE,
          xlab = "Number of individuals",
          ylab = "Number of species",
          main = "Rarefaction curves: Control vs Focal")

# Add Focal curves
rarecurve(mat_focal,
          step = 1,
          col = "blue",
          cex = 0.6,
          label = FALSE,
          add = TRUE)

# Add legend
legend("bottomright",
       legend = c("Control", "Focal"),
       col = c("orange", "blue"),
       lwd = 2,
       bty = "n")

```
```{r}
# Control
rarecurve(bee_matrix[bee_data$site == "control", ],
          step = 1,
          col = "orange",
          cex = 0.6,
          label = FALSE)

# Focal
rarecurve(bee_matrix[bee_data$site == "focal", ],
          step = 1,
          col = "blue",
          cex = 0.6)

```

```{r}
# Rarefied richness at standardized sample size
min_samples <- min(rowSums(bee_matrix))  # or a fixed N
bee_data$rare_rich <- rarefy(bee_matrix, sample = min_samples)

```

